### ISSUE TITLE
Reporte Practica 1 - Sprint  4

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/conexion-de-bases-de-datos-equipo-fgr#1]
[Práctica 1 - Sprint4.pdf](https://github.com/SistemasTecTlaxiaco/conexion-de-bases-de-datos-equipo-fgr/files/6750944/Practica.1.-.Sprint4.pdf)

**Comment by uzias10** [comment]
Muy buen trabajo, cumple con la rubrica.
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
